/// Flutter icons InsertUrlIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  InsertUrlIcon
///      fonts:
///       - asset: fonts/InsertUrlIcon.ttf
///
/// 
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
///
import 'package:flutter/widgets.dart';

class InsertUrlIcon {
  InsertUrlIcon._();

  static const _kFontFam = 'InsertUrlIcon';
  static const String? _kFontPkg = null;

  static const IconData link = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
